CREATE TABLE IF NOT EXISTS datecalc (
	dateId VARCHAR(50) NOT NULL PRIMARY KEY,
	dateName VARCHAR(50),
	year INT(50) DEFAULT 0 NOT NULL,
	month INT(50) DEFAULT 0 NOT NULL,
	day INT(50)DEFAULT 0 NOT NULL
);